# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 488c6b4f86cfb596c5d5dc0b317c1025303cfe1efa2763f33c35c23a7710a052b943b1c6cdc0a946ebde107fcb5c35de21e2391473a97ffba45cb40381e2f0e5

test:
  secret_key_base: b443d62865fd3a84c63edbbc1a1e96c4cc691a886cdf9faf1b0a73da2c34f46b06f5d65298ed545946bee3500f935ef12070cd34a6c6a00c5a250af24800f0dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
